### ISSUE TITLE
Install Error when I run npm install

### ISSUE THREAD

**Issue by jrnovak** [miroslavpejic85/mirotalk#32]
root@cleanubuntu:~/mirotalk# npm install
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```logs
> ngrok@4.0.1 postinstall /root/mirotalk/node_modules/ngrok
> node ./postinstall.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/root/mirotalk/node_modules/ngrok/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@4.0.1 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@4.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-11T16_16_34_709Z-debug.log
root@cleanubuntu:~/mirotalk# mc

root@cleanubuntu:~/mirotalk# 
```

**Comment by Jaideep25** [comment]
Hey @jrnovak welcome!
Could you please confirm that you made the .env file and all the details are filled up correctly? and could you please update your npm to 7.16.0 and try again?

**Comment by jrnovak** [comment]
That fixed it!

**Comment by miroslavpejic85** [comment]
Hey @jrnovak welcome! Good! Thanks @Jaideep25 😉

**Comment by Jaideep25** [comment]
@miroslavpejic85 you can close this issue now ;)
